services:
  rapigo-web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "31080:80"
    networks:
      - rapigo-network

networks:
  rapigo-network:
    driver: bridge
